config/routes.rb
Rails.application.routes.draw do

  #api routes
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      post 'create_tweet', to: 'tweets#create_api_tweet', as: 'create_tweet'
      get 'news', to: 'tweets#news', as: 'tweets'
      get '/:date1/:date2', to: 'tweets#by_dates', as: 'by_dates'
    end
  end
  
  #activeadmin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  #devise
  devise_for :user
  
  #nested routes users adn tweets
  resources :users do
    resources :tweets, except: [:index]
  end

  #root
  root 'tweets#index'
  get 'home/suspended', to: 'home#index', as: 'suspended'

  
  #create routes
  post '/follows/:id', to: 'follows#create', as:'create_follow' #requiero del id del usuario
  post '/likes/:id', to: 'likes#create', as:'create_like' #requiero de id del tweet
  post '/tweets/:id', to: 'tweets#retweet', as:'create_retweet' #requiero del id del tweet
  
  #destroy routes
  delete '/likes/:id', to:'likes#destroy', as:'destroy_like' #quiero el id del tweet
  delete '/follows/:id', to:'follows#destroy', as:'destroy_follow' #quiero el id del user
end

app/controllers/api/v1/tweets_controller.rb
module Api
    module V1
        class TweetsController < V1Controller

            include ActionController::HttpAuthentication::Basic::ControllerMethods
            http_basic_authenticate_with name: "superman", password: "123123", except: [:news, :by_dates]

            def news
                tweets = Tweet.last(50)
                @api_tweets = tweets.as_json(
                    only: %i[id content user_id],
                    methods: %i[like_count retweets_count retwitted_from]
                )
                render json: @api_tweets
            end

            def create_api_tweet
                @tweet = User.find(2).tweets.create(params_tweet)
                
                if @tweet.save
                    render json: @tweet, status: :created
                else
                    render json: @tweet.errors, status: :unprocessable_entity 
                end
            end

            def by_dates
                tweets = Tweet.since_date(params[:date1]).until_date(params[:date2])
                @api_tweets = tweets.as_json(
                    only: %i[id content user_id created_at],
                    methods: %i[like_count retweets_count retwitted_from]
                )
                render json: @api_tweets
            end

            private

            def params_tweet
                params.require(:tweet).permit(:content)
            end

        end
    end
end

app/views/tweets/_allTweets.html.erb
<div class="mt-2">
    <div class="tweets container">
        <% tweets.each do |tweet| %>
            <!--user photo -->
            <div class="row bg-light rounded-pill">
                <div class="col-md-2 p-0 m-0">
                    <%= image_tag tweet.user.photo, class:'img-profile-unlogged' %>
                </div>
                <div class="col-md-10">
                    <div class="row pt-3">
                    <!--like and retweet if user is logged -->
                        <% if user_signed_in? %>
                            <!--like button-->
                            <div class="like col-md-3 text-center">
                                    <div class="row">
                                        <div class="col-md-4 p-0">
                                            <div class="d-flex justify-content-end font-weight-bold text-primary"><%= tweet.like_count%></div>
                                        </div>
                                        <% if tweet.liked?(@user) %>
                                            <div class="col-md-8 pr-5 pl-0">
                                                <%= link_to destroy_like_path(tweet), method: :delete do %>
                                                    <div class="text-danger"><%= svg('heart-fill')%> Dislike</div>
                                                <% end %>
                                            </div>
                                        <% else %>
                                            <div class="col-md-8 padding-like pl-0">
                                                <%= link_to create_like_path(tweet), method: :post do %>
                                                    <div class="text-danger"><%= svg('heart')%> Like</div>
                                                <% end %>
                                            </div>
                                        <% end %>
                                    </div>
                            </div>
                            <!--retweet button-->
                            <div class="col-md-2 text-center">
                                <div class="rt row">
                                    <div class="col-md-4 p-0">
                                        <div class="font-weight-bold text-primary d-flex justify-content-end pr-2"><%= tweet.retweets_count %></div>
                                    </div>
                                    <div class="col-md-8 pr-5 pl-0">
                                        <%= link_to create_retweet_path(tweet) ,method: :post do %>
                                            <div class="d-flex justify-content-start"><%= svg('retweet') %> Rt</div>
                                        <% end %>
                                    </div>
                                </div>
                            </div>
                        <% else %>
                        <!-- like and retweet if user isn't logged -->
                            <!--like button-->
                            <div class="like col-md-3 text-center">
                                <div class="row">
                                    <div class="col-md-4 p-0">
                                        <div class="d-flex justify-content-end font-weight-bold text-primary"><%= tweet.like_count%></div>
                                    </div>
                                    <div class="col-md-8 pr-5 pl-0">
                                        <%= link_to new_user_session_path do %>
                                            <div class="col-md-8 padding-like pl-0 text-danger"><%= svg('heart-fill')%> Like</div>
                                        <% end %>
                                    </div>
                                </div>
                            </div>
                            <!--retweet button-->
                            <div class="like col-md-4 text-center">
                                <div class="row">
                                    <div class="col-md-3 p-0">
                                        <div class="font-weight-bold text-primary d-flex justify-content-end pr-2"><%= tweet.retweets_count %></div>
                                    </div>
                                    <div class="col-md-9 p-0 d-flex justify-content-start">
                                        <%= link_to new_user_session_path do %>
                                            <div class="text-info pl-0"><%= svg('retweet') %> Rt</div>
                                        <% end %>
                                    </div>
                                </div>
                            </div>   
                        <% end %>
                        <!-- date of the tweet -->
                        <div class="date col-md-4">
                            <% if user_signed_in? %>
                                <%= link_to user_tweet_path(@user, tweet) do %>
                                    <p><%=time_ago_in_words(tweet.created_at) %> ago</p>
                                <% end %>
                            <% else %>
                                <%= link_to new_user_session_path do %>
                                    <p><%=time_ago_in_words(tweet.created_at) %> ago</p>
                                <% end %>
                            <% end %>
                        </div>
                    </div>
                    <!-- content container -->
                    <div class="row m-5 py-3 rounded-pill">
                        <div class="content col-md h6">
                            <% if !tweet.tweet_id.nil? %>
                                <div class="text-primary m-0 p-0"><%= "RT @#{tweet.user.name}'s tweet" %></div>
                            <% else %>
                                <div class="text-primary m-0 p-0"><%= "@#{tweet.user.name}" %></div>
                            <% end %>
                            <%= hashtag(tweet.content) %>
                        </div>
                    </div>
                </div>
            </div>
            <br>
        <% end %>
    </div>
    <div class="d-flex justify-content-center">
        <%= paginate @tweets %>
    </div>
</div>

app/views/tweets/_allTweetsunlogged.html.erb
<div class="mt-2">
    <div class="tweets container">
        <% tweets.each do |tweet| %>
            <!--user photo -->
            <div class="row bg-light rounded-pill">
                <div class="col-md-2 p-0 m-0">
                    <%= image_tag tweet.user.photo, class:'img-profile-unlogged' %>
                </div>
                <div class="col-md-10">
                    <div class="row pt-3">
                            <!--like button-->
                            <div class="like col-md-3 text-center">
                                <div class="row">
                                    <div class="col-md-4 p-0">
                                        <div class="d-flex justify-content-end font-weight-bold text-primary"><%= tweet.like_count %></div>
                                    </div>
                                    <div class="col-md-8 pl-0">
                                        <%= link_to new_user_session_path do %>
                                            <div class="col-md-8 pl-0 text-danger"><%= svg('heart-fill')%> Like</div>
                                        <% end %>
                                    </div>
                                </div>
                            </div>
                            <!--retweet button-->
                            <div class="like col-md-4 text-center">
                                <div class="row">
                                    <div class="col-md-3 p-0">
                                        <div class="font-weight-bold text-primary d-flex justify-content-end pr-2"><%= tweet.retweets_count %></div>
                                    </div>
                                    <div class="col-md-9 p-0 d-flex justify-content-start">
                                        <%= link_to new_user_session_path do %>
                                            <div class="text-info pl-0"><%= svg('retweet') %> Rt</div>
                                        <% end %>
                                    </div>
                                </div>
                            </div>
                            <!-- date of the tweet -->
                            <div class="date col-md-4">
                                <% if user_signed_in? %>
                                    <%= link_to user_tweet_path(@user, tweet) do %>
                                        <p><%=time_ago_in_words(tweet.created_at) %> ago</p>
                                    <% end %>
                                <% else %>
                                    <%= link_to new_user_session_path do %>
                                        <p><%=time_ago_in_words(tweet.created_at) %> ago</p>
                                    <% end %>
                                <% end %>
                            </div>
                    </div>
                    <!-- content container -->
                    <div class="row m-5 py-3 rounded-pill">
                        <div class="content col-md h6">
                            <% if !tweet.tweet_id.nil? %>
                                <div class="text-primary m-0 p-0"><%= "RT @#{tweet.user.name}'s tweet" %></div>
                            <% else %>
                                <div class="text-primary m-0 p-0"><%= "@#{tweet.user.name}" %></div>
                            <% end %>
                            <%= hashtag(tweet.content) %>
                        </div>
                    </div>
                </div>
            </div>
            <br>
        <% end %>
    </div>
    <div class="d-flex justify-content-center">
        <%= paginate @tweets %>
    </div>
</div>

app/views/tweets/_followedTweets.html.erb
<div class="mt-2">
    <div class="tweets container">
        <% tweets.each do |tweet| %>
            <% if @user.followed_users.include? tweet.user or tweet.user == @user%> <!--#TODO ver si es necesario el OR-->
                <!--user photo -->
                <div class="row bg-light rounded-pill">
                    <div class="col-md-2 p-0 m-0">
                        <%= image_tag tweet.user.photo, class:'img-profile-logged' %>
                    </div>
                    <div class="col-md-10">
                        <div class="row pt-3">
                        <!--like and retweet if user is logged -->
                            <% if user_signed_in? %>
                                <!--like button-->
                                <div class="like col-md-3 text-center">
                                        <div class="row">
                                            <div class="col-md-4 p-0">
                                                <div class="d-flex justify-content-end font-weight-bold text-primary"><%= tweet.like_count%></div>
                                            </div>
                                            <% if tweet.liked?(@user) %>
                                                <div class="col-md-8 pr-5 pl-0">
                                                    <%= link_to destroy_like_path(tweet), method: :delete do %>
                                                        <div class="text-danger"><%= svg('heart-fill')%> Dislike</div>
                                                    <% end %>
                                                </div>
                                            <% else %>
                                                <div class="col-md-8 padding-like pl-0">
                                                    <%= link_to create_like_path(tweet), method: :post do %>
                                                        <div class="text-danger"><%= svg('heart')%> Like</div>
                                                    <% end %>
                                                </div>
                                            <% end %>
                                        </div>
                                </div>
                                <!--retweet button-->
                                <div class="col-md-2 text-center">
                                    <div class="rt row">
                                        <div class="col-md-4 p-0">
                                            <div class="font-weight-bold text-primary d-flex justify-content-end pr-2"><%= tweet.retweets_count%></div>
                                        </div>
                                        <div class="col-md-8 pr-5 pl-0">
                                            <%= link_to create_retweet_path(tweet) ,method: :post do %>
                                                <div class="d-flex justify-content-start"><%= svg('retweet') %> Rt</div>
                                            <% end %>
                                        </div>
                                    </div>
                                </div>
                            <% else %>
                            <!-- like and retweet if user isn't logged -->
                                <!--like button-->
                                <div class="like col-md-3 text-center">
                                    <div class="row">
                                        <div class="col-md-4 p-0">
                                            <div class="d-flex justify-content-end font-weight-bold text-primary"><%= tweet.like_count %></div>
                                        </div>
                                        <div class="col-md-8 pr-5 pl-0">
                                            <%= link_to new_user_session_path do %>
                                                <div class="col-md-8 padding-like pl-0 text-danger"><%= svg('heart-fill')%> Like</div>
                                            <% end %>
                                        </div>
                                    </div>
                                </div>
                                <!--retweet button-->
                                <div class="like col-md-4 text-center">
                                    <div class="row">
                                        <div class="col-md-3 p-0">
                                            <div class="font-weight-bold text-primary d-flex justify-content-end pr-2"><%= tweet.retweets_count %></div>
                                        </div>
                                        <div class="col-md-9 p-0 d-flex justify-content-start">
                                            <%= link_to new_user_session_path do %>
                                                <div class="text-info pl-0"><%= svg('retweet') %> Rt</div>
                                            <% end %>
                                        </div>
                                    </div>
                                </div>   
                            <% end %>
                            <!-- date of the tweet -->
                            <div class="date col-md-4">
                                <% if user_signed_in? %>
                                    <%= link_to user_tweet_path(@user, tweet) do %>
                                        <p><%=time_ago_in_words(tweet.created_at) %> ago</p>
                                    <% end %>
                                <% else %>
                                    <%= link_to new_user_session_path do %>
                                        <p><%=time_ago_in_words(tweet.created_at) %> ago</p>
                                    <% end %>
                                <% end %>
                            </div>
                        </div>
                        <!-- content container -->
                        <div class="m-5 h6">
                            <% if !tweet.tweet_id.nil? %>
                                <div class="text-primary m-0 p-0"><%= "RT @#{tweet.user.name}'s tweet" %></div>
                            <% else %>
                                <div class="text-primary m-0 p-0"><%= "@#{tweet.user.name}" %></div>
                            <% end %>
                            <br>
                            <%= hashtag(tweet.content) %>
                        </div>
                    </div>
                </div>
                <br>
            <% end %>
        <% end %>
        <div class="d-flex justify-content-center">
            <%= paginate @tweets %>
        </div>
    </div>
</div>

app/views/tweets/_form.html.erb
<h1 class="text-light text-center">Comment in <span class="font-italic text-primary font-weight-bold">Twitter.Project</span></h1>
<div class="container px-5">
    <%= form_with(model: [@user, tweet], local: true) do |f| %>
        <% if tweet.errors.any? %>
            <div id="error_explanation" class="text-light">
                <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>
                <ul>
                    <% tweet.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>
    
        <div class="form-group" readonly>
            <%= f.label :content %>
            <%= f.text_area :content, size: "70x5", class:'form-control form-control-lg', placeholder: "What's new?"  %>
        </div>

        <div class="actions">
            <%= f.submit "Tweet!",class:'btn btn-outline-light'%>
        </div>
    <% end %>
</div>

app/views/tweets/index.html.erb
<div class="mt-5 pt-2">
    <div class="row">
        <% if user_signed_in? %>
            <div class="col-2">
                <%= render template: :'users/index' %>
            </div>
            <div class="col-10">
                <div>
                    <%= render 'form', tweet: @tweet %>
                </div>
                <div class="d-flex justify-content-center">
                    <%= paginate @tweets %>
                </div>
                <% if params[:q].nil? %>
                        <%= render 'followedTweets', tweets: @tweets %>
                <% else %>
                        <%= render 'allTweets', tweets: @tweets %>
                <% end %>
            </div>
        <% else %>
            <div>
                <h1 class="text-light text-center pb-3"> Le <span class="font-italic text-primary font-weight-bold">Twitter.Clone</span></h1>
                <div class="d-flex justify-content-center">
                    <%= paginate @tweets %>
                </div>
                <div class="container container-welcome">
                    <%= render 'allTweetsunlogged', tweets: @tweets %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/tweets/show.html.erb
<% if user_signed_in? %>
    <div class="container text-light">
        <h1><%= "#{@tweet.user}" %></h1>
            <div class="row bg-light text-dark rounded-pill">
                <div class="col p-0 m-0">
                    <%= image_tag @tweet.user.photo, class:'img-show-logged' %>
                </div>
                <div class="col pt-3">
                    <h4>Comment</h4>
                    <%= @tweet.content %>
                </div> 
                <div class="col pt-3">
                    <h4>Publicated </h4>
                    <p></p><%=time_ago_in_words(@tweet.created_at)%> ago
                </div>
                <div class="col pt-3">
                    <h4>Likes</h4>
                    <%= @tweet.like_count %>
                </div>
            </div>

        <h5 class="mt-3 font-weight-bold">Users who likes this tweet</h5>
        <% Tweet.liker_users(@tweet, @users).each do |user|%>
            <%= image_tag user.photo , class:'img-show-logged-followers' %>
        <% end %>
    </div>

    <div class="container my-4"><%= link_to 'Back to Tweets', root_path %></div>
<% end %>    