config/routes.rb
Rails.application.routes.draw do

  #api routes
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      post 'create_tweet', to: 'tweets#create_api_tweet', as: 'create_tweet'
      get 'news', to: 'tweets#news', as: 'tweets'
      get '/:date1/:date2', to: 'tweets#by_dates', as: 'by_dates'
    end
  end
  
  #activeadmin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  #devise
  devise_for :user
  
  #nested routes users adn tweets
  resources :users do
    resources :tweets, except: [:index]
  end

  #root
  root 'tweets#index'
  get 'home/suspended', to: 'home#index', as: 'suspended'

  
  #create routes
  post '/follows/:id', to: 'follows#create', as:'create_follow' #requiero del id del usuario
  post '/likes/:id', to: 'likes#create', as:'create_like' #requiero de id del tweet
  post '/tweets/:id', to: 'tweets#retweet', as:'create_retweet' #requiero del id del tweet
  
  #destroy routes
  delete '/likes/:id', to:'likes#destroy', as:'destroy_like' #quiero el id del tweet
  delete '/follows/:id', to:'follows#destroy', as:'destroy_follow' #quiero el id del user
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  
  #tweet and like relations
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy

  #follows relations
  #followed side
  has_many :follows, dependent: :destroy
  has_many :followers, through: :follows

  #follower side
  has_many :inverse_follows, class_name: 'Follow', foreign_key: 'follower_id', dependent: :destroy
  has_many :followed_users, through: :inverse_follows, source: :user

  #custom methods
  def to_s
    self.name
  end

  #list of follewed users
  def self.followed_list(user) #TODO metodo provisional para encontrar usuarios a los  que sigo
    user.followed_users
  end

  #count retweets
  def RT_count
    self.tweets.count {|tweet| !tweet.tweet_id.nil?}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def suspended
    end

    def show
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="pt-5 margin-follows text-light">
    <h6 class="text-center mb-4 font-weight-bold bg-primary rounded-pill py-2">T.P community</h6>
    <% @users.each do |user| %>
        <% if user != current_user%>
            <div class="row pl-2 py-1">
                <div class="col-2">
                    <%= image_tag user.photo, class:'img_follows align-middle' %>
                </div>
                <div class="col-10 font-weight-bold pl-5 pt-3">
                    <% if user.followers.include? current_user%>
                        <%= link_to 'Unfollow', destroy_follow_path(user), method: :delete, class:'text-danger center' %>
                    <% else %>
                        <%= link_to 'Follow', create_follow_path(user), method: :post, class: 'text-primary' %>
                    <% end %>
                </div>
            </div>
        <% end %>    
    <% end %>
</div>